### PR TITLE
`nixosModules` should be out of `eachDefaultSystem`

### PR DESCRIPTION
**Pull request by drupol**
It is currently impossible to use this flake in my configuration because the output of the flake is wrong.

`nixosModules` should be out of `eachDefaultSystem` function.

### CODE REVIEW

**Comment by jbuchermn** [comment]
Thanks a lot for pointing this out!

**Comment by drupol** [comment]
There is another issue... I'm working on it right now.

**Comment by drupol** [comment]
I won't be able to finish in time today, I'll submit another PR as soon as I'm back on a computer.

**Comment by drupol** [comment]
See https://github.com/jbuchermn/guacamole-nixos/pull/2 for a work in progress

**Pull request merged**
